from django.db import models

class Dosen(models.Model):
    nama = models.CharField(max_length=50)
    NIP = models.CharField(max_length=50,unique=True)
    nilai_1 = models.FloatField(default=0)
    nilai_2 = models.FloatField(default=0)
    nilai_3 = models.FloatField(default=0)
    nilai_4 = models.FloatField(default=0)
    nilai_5 = models.FloatField(default=0)
    nilai_6 = models.FloatField(default=0)
    nilai_7 = models.FloatField(default=0)
    nilai_8 = models.FloatField(default=0)
    nilai_9 = models.FloatField(default=0)
    nilai_10 = models.FloatField(default=0)
    nilai_11 = models.FloatField(default=0)
    nilai_12 = models.FloatField(default=0)
    nilai_13 = models.FloatField(default=0)
    nilai_14 = models.FloatField(default=0)
    nilai_15 = models.FloatField(default=0)
    nilai_16 = models.FloatField(default=0)
    nilai_17 = models.FloatField(default=0)
    cluster = models.IntegerField(default=0)