# Generated by Django 2.1.3 on 2018-11-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181104_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='cluster',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nilai_1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nilai_10',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nilai_11',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nilai_12',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nilai_13',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nilai_14',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nilai_15',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nilai_16',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nilai_17',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nilai_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nilai_3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nilai_4',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nilai_5',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nilai_6',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nilai_7',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nilai_8',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nilai_9',
            field=models.FloatField(default=0),
        ),
    ]
