# Generated by Django 2.1.3 on 2018-11-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181105_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='nama',
            field=models.CharField(max_length=50),
        ),
    ]
