# Generated by Django 2.1.3 on 2018-11-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181105_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='kelas',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='kode_mk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='mata_kuliah',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
